export PS1="%1~ %# "

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
# 直前と同じコマンドを履歴に保存しない
setopt hist_ignore_dups
# 履歴全体から重複を削除
setopt hist_ignore_all_dups
# 複数のzshセッション間で履歴を共有
setopt share_history

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
  source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

autoload -Uz compinit
compinit -u
